config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :posts do 
    resources :comments 
  end
  resources :categories, only: [:index, :new, :create]

get 'users' => 'users#index'
get 'posts' => 'posts#index'

get 'posts' => 'posts#show'
get 'posts' => 'posts#new' # 要不要加這行???

get '/register', to: 'users#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'
  root 'posts#index'

resources :posts, except: [:destroy] do
  member do   # 客製化連結
    post :vote  # 這樣會產出 posts/1/vote
  end

  resources :comments, only: [:create, :show] do
    member do
      post :vote # 產出 posts/1/comments/1/vote
    end
  end
end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :connections
  has_many :posts, through: :connections

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #include Voteable
  belongs_to :user
  belongs_to :post
#  has_many :categories, through: :connections
# comment 不用 category
	validates :content, presence: true, length: {minimum: 5} # setting users when creating new post and comment objects
	has_many :votes, as: :voteable

	def up_votes
  	self.votes.where(vote: true).length
  end
  
  def down_votes
  	self.votes.where(vote: false).length
  end

  def total_votes
    up_votes - down_votes
  end

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
 end

app/models/post.rb
class Post < ActiveRecord::Base
#  include Voteable
  belongs_to :user #post 屬於user； user 對 post 一對多
  has_many :comments	# 一個 post 有很多個 comments
  has_many :connections # setting users when creating new post and comment objects
  has_many :categories, through: :connections 
  # post to category are n-n , connection is jointable
  has_many :votes, as: :voteable

  def up_votes
  	self.votes.where(vote: true).length
  end
  
  def down_votes
  	self.votes.where(vote: false).length
  end

  def total_votes
    up_votes - down_votes
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts		# user 對 post 一對多
  has_many :comments	# user 對 comment 一對多
	has_many :votes
	has_secure_password validations: false 
# setting users when creating new post and comment objects
	validates :name, presence: true, uniqueness: true
	validates :password, presence: true, on: :create, length: {minimum: 5}
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :creator, foreign_key: :user_id, class_name: "User"  # 用creator 取代user
  belongs_to :voteable, polymorphic: true # 重點

  validates_uniqueness_of :creator, scope: [:voteable_type, :voteable_id]	# 資料驗證
end

# voets/1/post

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:notice] = "You must be logged in to do that!"
      redirect_to :back
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
# 所有controller都繼承ApplicationController這個class
	def index
		@categories = Category.all
	end

  def new
    @category = Category.new
  end
  
	def create
	  @category = Category.new(category_params)

	  if @category.save!
	    redirect_to root_path
	  else
	    render :new
	  end
	end

	private 

	def category_params
	  params.require(:category).permit(:name)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
# 所有controller都繼承ApplicationController這個class
  def index
    @comments = Comment.all
    # 要先新增users這個table
  end
# added comment form in post show page／13  app/controllers/comments_controller.rb
	def create
	  @post = Post.find(params[:post_id])
	  @comment = @post.comments.build(params.require(:comment).permit(:content))
	 	@comment.user = current_user	# setting users when creating new post and comment objects
	  if @comment.save
	    redirect_to post_path(@post)
	  else
	    render 'posts/show'
	  end
	end

	def vote
	  @comment = Comment.find(params[:id])
	  @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

	  if @vote.valid?
	    flash[:success] = 'Your vote was counted!'
	  else
	    flash[:error] = "You can only vote for this comment once!".html_safe
	  end
	  redirect_to :back
	end

end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
# 所有controller都繼承ApplicationController這個class
  def index
    @connections = Connection.all
    # 要先新增users這個table
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# 所有controller都繼承ApplicationController這個class
  def index
    @posts = Post.all.sort_by {|x| x.total_votes }.reverse
    # @posts = Post.all   # 右邊是連到mbdel；mbdel連到db;@posts是區域變數，連到view;s與否是表示找到的資料是否是一筆
    # view --> controller --> modle    
    # 排序用
    @post = Post.find(1)
    # 要先新增users這個table
    # 意即去 Post model，也就是 posts table 找出每一筆資料，存進 @posts 變數
  end

  #在 Post Controller 裡面新增 show
  def show
    #Rails 會把用戶所有傳進來的參數打包成一個叫 params 的 Hash
    #find 代表搜尋某一比資料，而 params[:id] 代表用戶想查詢的資料 id

    @post = Post.find(params[:id])
    # post 改為posts 
    # added comment form in post show page／13  app/controllers/comments_controller.rb
    @comment = Comment.new
    @comments = @post.comments.all.sort_by {|x| x.total_votes }.reverse
  end
  
# 講義8,為了show留言

# 以下為 實作 Post 表單
  def new
    #產出一個空白物件(一筆空白資料)，並顯示在 posts/new 頁面
    @post = Post.new
  end

  def create
    #前端使用者傳回的資料，建立一個新的 post 物件
    post = Post.new(post_params)
    post.user = current_user # setting users when creating new post and comment objects
    #如果成功存進資料庫，就導回 index 頁面，失敗就再顯示一次表單
    if post.save!
      redirect_to posts_path
    else
      render :new
    end
  end

  def vote
     @post = Post.find(params[:id])
     @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
 
     if @vote.valid?
       flash[:success] = 'Your vote was counted!'
     else
        flash[:error] = "You can only vote for #{@post.title} once!".html_safe
     end
 
     redirect_to :back
  end

  private

  #確保 params 裡面的 post hash 存在，並且允許 title 和 content 被存取
  def post_params
    params.require(:post).permit(:title, :content, category_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
    user = User.find_by(name: params[:name])

    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = "You've logged in!"
        redirect_to root_path
    else
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
# 所有controller都繼承ApplicationController這個class
def show
  @user = User.find(params[:id])
end
  def new
  	#binding.pry
    @user = User.new
    # 要先新增users這個table
  end
  def create
  	@user = User.new(user_params)
 
  	if @user.save
    	binding.pry
    	redirect_to root_path
   	else
    	render :new
   	end
 	end
 
	private 
 
	def user_params
   params.require(:user).permit(:name, :password)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<% if category.title == 'Ruby' %>
  <span class='badge alert-danger'>
<% elsif category.title == 'Funny' %>
  <span class='badge alert-success'>
<% elsif category.title == 'News' %>
  <span class='badge progress-bar-info'>
<% elsif category.title == 'Javascript' %>
  <span class='badge progress-bar-warning'>
<% elsif category.title == 'Git' %>
  <span class='badge progress-bar-primary'>
<% end %>
  <%= category.title %>
</span>

app/views/categories/index.html.erb
<%= render 'shared/title', title: 'All Categories'%>

<% @categories.each do |category| %>
<div class='row'>
  <div class='well col-md-6'>
    <p><%= category.name %></p>
  </div>
</div>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/title', title: "Create New Category"%>

<div class="well col-md-6">
  <%= form_for @category do |c| %>
    <div class="form-group">
    	<%= c.label :category_name %>
    	<br>
    	<%= c.text_field :name %>
    </div>
    <%= c.submit 'Create Category', class: 'btn btn-primary' %>
  <% end %>
</div> 

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
    <div class="navbar-header">
       <%= link_to "PostBoard", root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
        <% else %>
          <li><%= link_to 'Register', register_path %></li>
        <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
              <%= current_user.name %> <span class='caret'></span>
              <% end %>
              <ul class="dropdown-menu">
                <li><%= link_to 'User Profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
       </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pro3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%= render 'layouts/navigation' %>
	</header>
<!--added container css class, clean up the code a bit/ 12  app/views/layouts/application.html.erb-->
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<%= render 'layouts/messages' %>
				<%= yield %>
			</div>
		</div>
	</div>	
</body>
</html>

app/views/posts/_post.html.erb
<div class="row">
  <div class='col-md-1 well text-center'>
     <% if logged_in? %>

       <%= link_to vote_post_path(post, vote: true), class: "btn btn-primary", method: 'post' do %>
        Like
       <% end %>
      <%end %>
    <br/>
    <%= post.total_votes %> Votes
    <br/>

    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), class: "btn btn-danger", method: 'post' do %>
      Dislike
      <% end %>
     <% end %>
 </div>
   <div class="well col-md-6">
     <%= render partial: "categories/category", collection: post.categories %>
     <p>
       <h4><%= post.title %></h4>
     </p>
     <p>
       <%= post.content %>
     </p>
     <br>
     <span>
       <%= link_to "show this post", post_path(post) %>
     </span>
   </div>
 </div> 

<!-- <div class="row">
  <div class="well col-md-6">
    <%= render partial: "categories/category", collection: post.categories %>
    <p>
      <h4><%= post.title %></h4>
    </p>
    <p>
      <%= post.content %>
    </p>
    <br>
    <span>
      <%= link_to "show this post", post_path(post) %>
    </span>
  </div>
</div>  -->

app/views/posts/index.html.erb
<%= render 'shared/title', title: 'Post List'%><!--傳值進去變數-->
<!-- <h1>Posts List</h1> 刪這行加上行，View Partial用法-->
<h3>All Posts</h3>

<% @posts.each do |post| %>  <!--對應到Controller的post_controller.rb-->
<%= render 'post', post: post %><!--呼叫同一資料夾的_post.html.erb-->
<!--created post partial下面全刪了
  <div class="row">
    <div class="well col-md-6">
      <p><h4><%= post.title %></h4></p>
      <p><%= post.content %></p>
      <br>
      <span>
        <%= link_to "show this post", posts_path(post) %>
      </span>
    </div>
  </div>
  -->
<% end %>

<!--以下08 ptt 最後-->
<!-- 第二版
<% @posts.each do |post| %>
  <div class="row">
    <div class="well col-md-6">
      <p>
        <h4><%= post.title %></h4>
      </p>
      <p>
        <%= post.content %>
      </p>
      <br>
      <span>
        <%= link_to "show this post", posts_path(post)%>
        <!--何意？要加=嗎--
      </span>
    </div>
  </div>
<% end %>
以上為加了Bootstrap後的用法
<!-- 第一版
<hr>
<% @posts.each do |post| %>
<div>
  <div>
    <!-- 顯示 post.title 和 content --
    <p><%= post.title %></p>
    <p><%= post.content %></p>
    <span>
      <!-- link_to 會產生出 html <a> tag --
      <%= link_to "show post", posts_path(post)%>
      <!-- post_path加了s就browser出來了 --
      <!-- 在http://localhost:3000/info 查出來的，感謝 --
    </span>
  </div>
</div>
<% end %>
-->

app/views/posts/new.html.erb
<%= render 'shared/title', title: 'New Post'%>

<div class="well col-md-12">
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <br>
      <%= f.text_area :content, rows: 5 %>
    </div>
    <div class="form-group">
       <%= f.label :categories %>
       <br>
       <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :title) do |cbox|%>
       <%= cbox.label(class: "checkbox-inline") { cbox.check_box(class: "checkbox") + cbox.text } %>
       <% end %>
    </div>
  <br>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>
<!--added post new action and form/20  app/views/posts/new.html.erb-->
<%= link_to 'Back to Post List', posts_path %> 

app/views/posts/show.html.erb
<%= render 'shared/title', title: "#{@post.title}"%>
<!-- added show action and view in posts controller/7  app/views/posts/show.html.erb-->
<!--beautify the html files a bit/ 21  app/views/posts/show.html.erb-->
<div class="row">
	<div class="col-md-8 well">
  <h4>category:
    <%= render partial: "categories/category", collection: @post.categories %></h4>
		<h3><%= @post.title %></h3>
		<p>
	 		<%= @post.content %>
	 	</p>
    <br>
    <small>posted by </small><%= @post.user.name %>
 	</div>
</div>
<!--added container css class, clean up the code a bit/36  app/views/posts/show.html.erb-->
<h4>All Comments:</h4>
<% @post.comments.each do |comment|%>
	<div class="row">

    <div class='col-md-1 well text-center'>
      <% if logged_in? %>
        <%= link_to vote_post_comment_path(@post, comment, vote: true), class: "btn btn-primary", method: 'post' do %>
          Like
        <% end %>
      <% end %>
      <br/>
      <%= comment.total_votes %> Votes
      <br/>
      <% if logged_in? %>
        <%= link_to vote_post_comment_path(@post, comment, vote: false), class: "btn btn-danger", method: 'post' do %>
          Dislike
        <% end %>
      <% end %>
    </div>

 		<div class="col-md-6 well">
 	  	<p>
 	   	 <%= comment.content%>
 	 	 	</p>
      <br>
      <small>commented by </small><%= "#{comment.user.name}" %>
 	 	 </div>
 	</div>
<% end %>
<!--added comment form in post show page/16  app/views/posts/show.html.erb-->
<% if logged_in? %><!--added logout path and login display conditions-->

  <h4>Leave a comment:</h4>
  <%= form_for [@post, @comment] do |f| %>
    <div class="row">
      <%= f.text_area :content, rows: 3, class: 'col-md-4' %>
      <div class="col-md-2">
        <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
      </div>
    </div>
    <br>
    <% end %>

<% end %>
  		  
<hr>

<div class="row">
	<%= link_to 'go back to all posts', posts_path %>
</div>

app/views/shared/_title.html.erb
<h3><%= title %></h3>
<hr>

app/views/users/index.html.erb
<h1>User List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<% %>
  <tbody>
<!-- 為何原本browers出不來？因為檔名後面多了一個空格 -->
  <!-- 1,%表ruby語法；2,%後面的= 是表示browser是否將之顯示出來。3,@users是去users_controller.rb裡捉「@users = User.all」的@users；@users = User.all表示將資料庫中User table all傳給變數@users -->
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.age %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h4>Register</h4>

<div class="well col-md-6">
  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password%>
  </div>
  <br>
  <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-primary') %>
	<% end %>
</div>

app/views/users/show.html.erb
<%= render 'shared/title', title: "#{@user.name}'s activities"%>

<h4><%= current_user.name %>'s posts:</h4>

<% @user.posts.each do |post| %>

<div class="row">
  <div class="col-md-8 well">
    <h3><%= post.title %></h3>
    <p>
      <%= post.content %>
    </p>
    <br>
    <small>posted by </small><%= " #{post.user.name}" %>
  </div>
</div>

<% end %>
<hr>
<h4><%= current_user.name %>'s comments:</h4>

<% @user.comments.each do |comment| %>
  <div class="row">
    <div class="col-md-6 well">
      <p>
        <%= comment.content %>
      </p>
      <br>
      <small>commented by </small><%= "#{comment.user.name}" %>
    </div>
  </div>
<% end %>

<%= link_to 'Back', root_path %>